// tools/genConferences.mjs — regenerate js/conferences.js from the ESPN groups API.
//
//   node tools/genConferences.mjs > js/conferences.js
//
// Conference realignment happens every couple of years and the map ships as a
// static file (the site's CSP only allows connections to Supabase), so it has
// to be rebuilt by hand when teams move. Everything not in FBS is left out on
// purpose: an FCS visitor simply contributes no conference term.
const SEASON = process.argv[2] || '2025';
const base = 'https://sports.core.api.espn.com/v2/sports/football/leagues/college-football';
const kids = await (await fetch(`${base}/seasons/${SEASON}/types/2/groups/80/children?limit=50`)).json();
const byConf = {};
for (const it of (kids.items || [])) {
  const g = await (await fetch(it.$ref.replace('http://', 'https://'))).json();
  const name = g.shortName || g.name;
  const tm = await (await fetch(g.teams.$ref.replace('http://', 'https://') + '&limit=100')).json();
  for (const ref of (tm.items || [])) {
    const td = await (await fetch(ref.$ref.replace('http://', 'https://'))).json();
    for (const key of [td.displayName, td.shortDisplayName, td.location, td.nickname]) {
      if (key) (byConf[name] = byConf[name] || new Set()).add(key);
    }
  }
}
let out = `// js/conferences.js — team -> FBS conference.\n//\n// GENERATED by tools/genConferences.mjs (season ${SEASON}) — do not hand-edit.\n`
        + `// The page cannot fetch this at runtime: the CSP allows connections only to\n`
        + `// Supabase, so the map ships as a static file the way logos.json does. Teams\n`
        + `// missing from it (FCS visitors, mostly) contribute no conference term.\n\n`
        + `export const TEAM_CONFERENCE = {\n`;
for (const c of Object.keys(byConf).sort()) {
  out += `  // ${c}\n`;
  for (const t of [...byConf[c]].sort()) out += `  ${JSON.stringify(t)}: ${JSON.stringify(c)},\n`;
}
out += `};\n\nexport function conferenceOf(team) {\n  return TEAM_CONFERENCE[String(team || '').trim()] || null;\n}\n`;
process.stdout.write(out);
